module.exports = {
  apps: [
    // Next.js Frontend
    {
      name: 'support-portal',
      script: './scripts/start-server.sh',
      interpreter: 'bash',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4002,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4002,
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
      wait_ready: true,
      listen_timeout: 10000,
    },

    // Email Service
    {
      name: 'email-service',
      cwd: './services/email-service',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4003,
      },
      error_file: '../../logs/email-service-error.log',
      out_file: '../../logs/email-service-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },

    // Notification Service (WebSocket + Workers)
    {
      name: 'notification-service',
      cwd: './services/notification-service',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4004,
      },
      error_file: '../../logs/notification-service-error.log',
      out_file: '../../logs/notification-service-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },

    // Calling Service
    {
      name: 'calling-service',
      cwd: './services/calling-service',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4005,
      },
      error_file: '../../logs/calling-service-error.log',
      out_file: '../../logs/calling-service-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },

    // Facebook Service
    {
      name: 'facebook-service',
      cwd: './services/facebook-service',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4006,
      },
      error_file: '../../logs/facebook-service-error.log',
      out_file: '../../logs/facebook-service-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },

    // Order Tracking Service
    {
      name: 'order-tracking-service',
      cwd: './services/order-tracking-service',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4007,
      },
      error_file: '../../logs/order-tracking-service-error.log',
      out_file: '../../logs/order-tracking-service-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      min_uptime: '10s',
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },

    // Database Backup Worker (Daily at 2:00 AM IST to MEGA)
    {
      name: 'backup-worker',
      script: './scripts/start-backup-worker.sh',
      interpreter: 'bash',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/backup-worker-error.log',
      out_file: './logs/backup-worker-out.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      min_uptime: '10s',
      max_restarts: 5,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 15000,
    },
  ],
};
